apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubeusers
  ports:
    - port: 3000
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      labels:
        app: kubeusers
    spec:
      containers:
        - name: kubecontainer
          image: perlucas/users-creator:v1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongodb://host.minikube.internal:27017
            - name: DB_NAME
              value: users-creator
          imagePullPolicy: Always
    